version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: db
    ports:
      - '6500:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always

volumes:
  progresDB:
