apiVersion: v1
kind: Service
metadata:
  name: cookooff-backend-service
spec:
  selector:
    app: cookooff-backend
  ports:
    - protocol: TCP
      port: 80 # The port on which the service will be exposed
      targetPort: 8080 # The port your Node.js app is listening on
  type: LoadBalancer # Change to 'NodePort' or 'ClusterIP' if needed
